/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppUsuariosConfiguracaoRouteImport } from './routes/_app/usuarios.configuracao'
import { Route as AppPlcsPlcIdRouteImport } from './routes/_app/plcs.$plcId'
import { Route as AppClpsConfiguracaoRouteImport } from './routes/_app/clps.configuracao'
import { Route as AppClpsPlcIdRouteImport } from './routes/_app/clps.$plcId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosConfiguracaoRoute = AppUsuariosConfiguracaoRouteImport.update({
  id: '/usuarios/configuracao',
  path: '/usuarios/configuracao',
  getParentRoute: () => AppRoute,
} as any)
const AppPlcsPlcIdRoute = AppPlcsPlcIdRouteImport.update({
  id: '/plcs/$plcId',
  path: '/plcs/$plcId',
  getParentRoute: () => AppRoute,
} as any)
const AppClpsConfiguracaoRoute = AppClpsConfiguracaoRouteImport.update({
  id: '/clps/configuracao',
  path: '/clps/configuracao',
  getParentRoute: () => AppRoute,
} as any)
const AppClpsPlcIdRoute = AppClpsPlcIdRouteImport.update({
  id: '/clps/$plcId',
  path: '/clps/$plcId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/clps/$plcId': typeof AppClpsPlcIdRoute
  '/clps/configuracao': typeof AppClpsConfiguracaoRoute
  '/plcs/$plcId': typeof AppPlcsPlcIdRoute
  '/usuarios/configuracao': typeof AppUsuariosConfiguracaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/clps/$plcId': typeof AppClpsPlcIdRoute
  '/clps/configuracao': typeof AppClpsConfiguracaoRoute
  '/plcs/$plcId': typeof AppPlcsPlcIdRoute
  '/usuarios/configuracao': typeof AppUsuariosConfiguracaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/clps/$plcId': typeof AppClpsPlcIdRoute
  '/_app/clps/configuracao': typeof AppClpsConfiguracaoRoute
  '/_app/plcs/$plcId': typeof AppPlcsPlcIdRoute
  '/_app/usuarios/configuracao': typeof AppUsuariosConfiguracaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/clps/$plcId'
    | '/clps/configuracao'
    | '/plcs/$plcId'
    | '/usuarios/configuracao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/clps/$plcId'
    | '/clps/configuracao'
    | '/plcs/$plcId'
    | '/usuarios/configuracao'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/clps/$plcId'
    | '/_app/clps/configuracao'
    | '/_app/plcs/$plcId'
    | '/_app/usuarios/configuracao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios/configuracao': {
      id: '/_app/usuarios/configuracao'
      path: '/usuarios/configuracao'
      fullPath: '/usuarios/configuracao'
      preLoaderRoute: typeof AppUsuariosConfiguracaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plcs/$plcId': {
      id: '/_app/plcs/$plcId'
      path: '/plcs/$plcId'
      fullPath: '/plcs/$plcId'
      preLoaderRoute: typeof AppPlcsPlcIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clps/configuracao': {
      id: '/_app/clps/configuracao'
      path: '/clps/configuracao'
      fullPath: '/clps/configuracao'
      preLoaderRoute: typeof AppClpsConfiguracaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clps/$plcId': {
      id: '/_app/clps/$plcId'
      path: '/clps/$plcId'
      fullPath: '/clps/$plcId'
      preLoaderRoute: typeof AppClpsPlcIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppClpsPlcIdRoute: typeof AppClpsPlcIdRoute
  AppClpsConfiguracaoRoute: typeof AppClpsConfiguracaoRoute
  AppPlcsPlcIdRoute: typeof AppPlcsPlcIdRoute
  AppUsuariosConfiguracaoRoute: typeof AppUsuariosConfiguracaoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppClpsPlcIdRoute: AppClpsPlcIdRoute,
  AppClpsConfiguracaoRoute: AppClpsConfiguracaoRoute,
  AppPlcsPlcIdRoute: AppPlcsPlcIdRoute,
  AppUsuariosConfiguracaoRoute: AppUsuariosConfiguracaoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
